version: '3.8'

services:
  scraper:
    build: .
    container_name: auto_ria_scraper
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    command: python main.py

  db:
    image: postgres:15
    container_name: auto_ria_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
